// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// /// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABw6nSDCHQO9SCBScdcOM6SALKny3D6Gk',
    appId: '1:1078667727770:web:2b0b03cc2e5b50fb66a023',
    messagingSenderId: '1078667727770',
    projectId: 'bus-tracking-dev',
    authDomain: 'bus-tracking-dev.firebaseapp.com',
    storageBucket: 'bus-tracking-dev.firebasestorage.app',
    measurementId: 'G-NS4HPL80YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Com-oQV5WZrb-dncFdY5Yo89TjioDUg',
    appId: '1:1078667727770:android:398d978cb946a07b66a023',
    messagingSenderId: '1078667727770',
    projectId: 'bus-tracking-dev',
    storageBucket: 'bus-tracking-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUh1rymfGIvvulNnZ2OPFAhvkJJpmbltw',
    appId: '1:1078667727770:ios:0a5c2bab4d730dad66a023',
    messagingSenderId: '1078667727770',
    projectId: 'bus-tracking-dev',
    storageBucket: 'bus-tracking-dev.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUh1rymfGIvvulNnZ2OPFAhvkJJpmbltw',
    appId: '1:1078667727770:ios:0a5c2bab4d730dad66a023',
    messagingSenderId: '1078667727770',
    projectId: 'bus-tracking-dev',
    storageBucket: 'bus-tracking-dev.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABw6nSDCHQO9SCBScdcOM6SALKny3D6Gk',
    appId: '1:1078667727770:web:f8436ca6511711c366a023',
    messagingSenderId: '1078667727770',
    projectId: 'bus-tracking-dev',
    authDomain: 'bus-tracking-dev.firebaseapp.com',
    storageBucket: 'bus-tracking-dev.firebasestorage.app',
    measurementId: 'G-MT6RZTEWVY',
  );

}